
-- --------------------------------------------------------

--
-- Table structure for table `catalyst`
--

CREATE TABLE `catalyst` (
  `nameId` int(6) NOT NULL DEFAULT 0,
  `nameId_kr` varchar(100) DEFAULT NULL,
  `nameId_en` varchar(100) NOT NULL,
  `input` int(6) NOT NULL DEFAULT 0,
  `input_kr` varchar(100) DEFAULT NULL,
  `input_en` varchar(100) NOT NULL,
  `successProb` int(3) NOT NULL DEFAULT 0,
  `broad` enum('true','false') NOT NULL DEFAULT 'false'
) ENGINE=InnoDB DEFAULT CHARSET=euckr COLLATE=euckr_korean_ci;

--
-- Dumping data for table `catalyst`
--

INSERT INTO `catalyst` (`nameId`, `nameId_kr`, `nameId_en`, `input`, `input_kr`, `input_en`, `successProb`, `broad`) VALUES
(16445, '영생의 빛', 'Eternal Light', 16440, '영혼을 잃은 활', 'Lost Soul Bow', 0, 'true'),
(16445, '영생의 빛', 'Eternal Light', 16441, '영혼을 잃은 체인소드', 'Lost Soul Chainsword', 0, 'true'),
(16445, '영생의 빛', 'Eternal Light', 16442, '영혼을 잃은 키링크', 'Lost Soul Kiringku', 0, 'true'),
(16445, '영생의 빛', 'Eternal Light', 16458, '영혼을 잃은 도끼', 'Lost Soul Axe', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17055, '\\aE마법서 (디스인티그레이트)(기운)', 'Spell Book (Disintegrate) (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17056, '\\aE기술서 (카운터 배리어)(기운)', 'Technical Book (Counter Barrier) (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17057, '\\aE정령의 수정 (소울 오브 프레임)(기운)', 'Spirit Crystal (Soul of Frame) (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17058, '\\aE흑정령의 수정 (아머 브레이크)(기운)', 'Black Spirit\'s Crystal (Armor Break) (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17059, '\\aE전사의 인장 (데스페라도)(기운)', 'Warrior\'s Seal (Desperado) (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17060, '마법서 (미티어 스트라이크)(기운)', 'Spell Book (Meteor Strike) (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17061, '정령의 수정 (어스 바인드)(기운)', 'Spirit Crystal (Earth Bind) (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17062, '정령의 수정 (폴루트 워터)(기운)', 'Spirit Crystal (Polute Water) (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17063, '정령의 수정 (스트라이커 게일)(기운)', 'Spirit Crystal (Striker Gale) (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17064, '전사의 인장 (타이탄: 락)(기운)', 'Warrior\'s Seal (Titan: Rock) (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17065, '전사의 인장 (타이탄: 매직)(기운)', 'Warrior\'s Seal (Titan: Magic) (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17066, '전사의 인장 (타이탄: 블릿)(기운)', 'Warrior\'s Seal (Titan: Bullet) (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17067, '정령의 수정 (허리케인)(기운)', 'Spirit Crystal (Hurricane) (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17068, '\\aE기술서 (카운터 배리어:베테랑)(기운)', 'Technical Book (Counter Barrier: Veteran) (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17069, '\\aE흑정령의 수정 (아머 브레이크:데스티니)(기운)', 'Black Spirit\'s Crystal (Armor Break: Destiny) (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17070, '\\aE전사의 인장 (데스페라도:앱솔루트)(기운)', 'Warrior\'s Seal (Desperado: Absolute) (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17091, '오리하루콘 단검(기운)', 'Oriharukon Dagger (Energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17092, '\\aF나이트발드의 양손검(기운)', 'Nightbald\'s Two-Handed Sword (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17093, '파괴의 장궁(기운)', 'Longbow of Destruction (Energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17094, '론드의 이도류(기운)', 'Londe\'s Dual Blade (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17095, '바포메트의 지팡이(기운)', 'Baphomet\'s Staff (Energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17096, '힘의 지팡이(기운)', 'Staff of Power (Energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17097, '마나의 지팡이(기운)', 'Staff of Mana (Energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17098, '얼음 여왕의 지팡이(기운)', 'Ice Queen\'s Staff (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17099, '데몬의 지팡이(기운)', 'Demon\'s Staff (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17100, '블러드서커(기운)', 'Blood Sucker (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17101, '극한의 체인소드(기운)', 'Extreme Chainsword (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17102, '냉한의 키링크(기운)', 'Cold Key Link (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17103, '데스나이트의 불검(기운)', 'Death Knight\'s Fire Sword (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17104, '커츠의 검(기운)', 'Kurtz\'s Sword (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17105, '제로스의 지팡이(기운)', 'Zero\'s Staff (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17106, '살기의 키링크(기운)', 'Key link to life (energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17121, '\\aF리치 로브(기운)', 'Rich Robe (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17122, '데스나이트의 갑옷(기운)', 'Death Knight\'s Armor (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17123, '흑장로의 로브(기운)', 'Black Elder\'s Robe (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17124, '커츠의 갑옷(기운)', 'Kurtz\'s Armor (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17125, '거대 여왕 개미의 금빛 날개(기운)', 'Golden wings (energy) of the giant queen ant', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17126, '거대 여왕 개미의 은빛 날개(기운)', 'Silver wings (energy) of the giant queen ant', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17127, '\\aF뱀파이어의 망토(기운)', 'Vampire\'s Cloak (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17128, '투명 망토(기운)', 'Invisibility Cloak (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17129, '신성한 보호 망토(기운)', 'Sacred Protective Cloak (Energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17130, '\\aF시어의 심안(기운)', 'Seer\'s Mind\'s Eye (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17131, '반역자의 방패(기운)', 'Traitor\'s Shield (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17132, '데스나이트의 부츠(기운)', 'Death Knight\'s Boots (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17133, '커츠의 부츠(기운)', 'Kurtz\'s Boots (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17134, '타락의 부츠(기운)', 'Boots of Corruption (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17135, '돌 장갑(기운)', 'Stone Gloves (Energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17136, '데스나이트의 장갑(기운)', 'Death Knight\'s Gloves (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17137, '커츠의 장갑(기운)', 'Kurtz\'s Gloves (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17138, '타락의 장갑(기운)', 'Gloves of Corruption (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17139, '\\aF머미로드의 왕관(기운)', 'Mommy Lord\'s Crown (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17140, '지휘관의 투구(기운)', 'Commander\'s Helmet (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17141, '데스나이트의 투구(기운)', 'Death Knight\'s Helmet (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17142, '발터자르의 모자(기운)', 'Balterzar\'s Hat (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17143, '카스파의 모자(기운)', 'Caspar\'s Hat (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17144, '메르키오르의 모자(기운)', 'Merchior\'s Hat (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17145, '세마의 모자(기운)', 'Sema\'s Hat (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17146, '커츠의 투구(기운)', 'Kurtz\'s Helmet (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17147, '마법방어 각반(기운)', 'Magic Defense Gaiters (Energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17148, '흑장로의 샌달(기운)', 'Black Elder\'s Sandals (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17149, '혼돈의 투구(기운)', 'Helmet of Chaos (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17150, '실프의 티셔츠(기운)', 'Sylph\'s T-shirt (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17151, '신성한 마법 방어 투구(기운)', 'Sacred Magic Defense Helmet (Energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17152, '\\aF아이리스의 부츠(기운)', 'Iris\' Boots (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17153, '\\aF머미로드의 장갑(기운)', 'Mummy Lord\'s Gloves (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17154, '\\aF쿠거의 가더(기운)', 'Cougar\'s Guarder (Aura)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17155, '\\aF우그누스의 가더(기운)', 'Ugnus\'s Guarder (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17156, '\\aF나이트발드의 각반(기운)', 'Nightbald\'s Gaiters (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17157, '\\aF아이리스의 각반(기운)', 'AIris\' Gaiters (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17158, '\\aF뱀파이어의 각반(기운)', 'Vampire\'s Gaiters (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17159, '\\aF격분의 장갑(기운)', 'Rage Gloves (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17161, '도펠겡어 보스의 목걸이(기운)', 'Doppelg?nger Boss\'s Necklace (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17162, '투사의 목걸이(기운)', 'Fighter\'s Necklace (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17163, '현자의 목걸이(기운)', 'Sage\'s Necklace (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17164, '빛나는 사이하의 목걸이(기운)', 'Shiny Saiha\'s Necklace (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17165, '오림의 목걸이(기운)', 'Orim\'s Necklace (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17166, '도펠겡어 보스의 왼쪽 반지(기운)', 'Doppelg?nger Boss\' Left Ring (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17167, '도펠겡어 보스의 오른쪽 반지(기운)', 'Doppelg?nger Boss\'s Right Ring (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17168, '라이아의 반지(기운)', 'Laia\'s Ring (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17169, '신성한 일격의 반지(기운)', 'Ring of Holy Strike (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17170, '\\aF제니스의 반지(기운)', 'Zenith\'s Ring (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17171, '마왕의 반지(기운)', 'Devil\'s Ring (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17172, '기백의 반지(기운)', 'Ring of Spirit (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17173, '세마의 반지(기운)', 'Sema\'s Ring (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17174, '지식의 반지(기운)', 'Ring of Knowledge (Energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17175, '완력의 반지(기운)', 'Ring of strength (energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17176, '민첩의 반지(기운)', 'Ring of Agility (Energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17177, '에이션트 자이언트의 반지(기운)', 'Ancient Giant\'s Ring (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17178, '크로노스의 벨트(기운)', 'Kronos\' Belt (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17179, '타이탄의 벨트(기운)', 'Titan\'s Belt (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17180, '\\aF단풍 반지(기운)', 'Maple Ring (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17181, '일격의 반지(기운)', 'Ring of Strike (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17182, '\\aF사신의 반지(기운)', 'Shinigami\'s Ring (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17183, '\\aF리치의 반지(기운)', 'Rich\'s Ring (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17184, '사신의 사념 조각(기운)', 'Shinigami\'s Thought Piece (Energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17185, '전설 무기 제작 비법서(기운)', 'Legendary Weapon Crafting Secret Book (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17186, '용의 심장(기운)', 'Dragon\'s Heart (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17187, '봉인된 오만의 탑 1층 이동 부적(기운)', 'Sealed Tower of Arrogance 1st floor movement talisman (energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17188, '봉인된 오만의 탑 2층 이동 부적(기운)', 'Sealed Tower of Arrogance 2nd floor movement talisman (energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17189, '봉인된 오만의 탑 3층 이동 부적(기운)', 'Sealed Tower of Arrogance 3rd floor movement talisman (energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17190, '봉인된 오만의 탑 4층 이동 부적(기운)', 'Sealed Tower of Arrogance 4th floor movement talisman (energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17191, '봉인된 오만의 탑 5층 이동 부적(기운)', 'Sealed Tower of Arrogance 5th floor movement talisman (energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17192, '봉인된 오만의 탑 6층 이동 부적(기운)', 'Sealed Tower of Arrogance 6th floor movement talisman (energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17193, '봉인된 오만의 탑 7층 이동 부적(기운)', 'Sealed Tower of Arrogance 7th floor movement talisman (energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17194, '봉인된 오만의 탑 8층 이동 부적(기운)', 'Sealed Tower of Arrogance 8th floor movement talisman (energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17195, '봉인된 오만의 탑 9층 이동 부적(기운)', 'Sealed Tower of Arrogance 9th floor movement talisman (energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17196, '봉인된 오만의 탑 10층 이동 부적(기운)', 'Sealed Tower of Arrogance 10th floor movement talisman (energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17197, '안타라스의 숨결(기운)', 'Antaras\' Breath (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17198, '발라카스의 숨결(기운)', 'Breath of Balakas (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17199, '파푸리온의 숨결(기운)', 'Pafurion\'s Breath (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 17200, '린드비오르의 숨결(기운)', 'Lindvior\'s Breath (Energy)', 0, 'true'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 25131, '하딘의 수정구(기운)', 'Hardin\'s Crystal Ball (Energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 25132, '오림의 수정구(기운)', 'Orim\'s Crystal Ball (Energy)', 0, 'false'),
(17053, '생명의 나뭇잎', 'Leaf of Life', 25133, '\\aH사신의 숨결(기운)', 'Reaper\'s Breath (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17055, '\\aE마법서 (디스인티그레이트)(기운)', 'Spell Book (Disintegrate) (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17056, '\\aE기술서 (카운터 배리어)(기운)', 'Technical Book (Counter Barrier) (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17057, '\\aE정령의 수정 (소울 오브 프레임)(기운)', 'Spirit Crystal (Soul of Frame) (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17058, '\\aE흑정령의 수정 (아머 브레이크)(기운)', 'Black Spirit\'s Crystal (Armor Break) (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17059, '\\aE전사의 인장 (데스페라도)(기운)', 'Warrior\'s Seal (Desperado) (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17060, '마법서 (미티어 스트라이크)(기운)', 'Spell Book (Meteor Strike) (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17061, '정령의 수정 (어스 바인드)(기운)', 'Spirit Crystal (Earth Bind) (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17062, '정령의 수정 (폴루트 워터)(기운)', 'Spirit Crystal (Polute Water) (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17063, '정령의 수정 (스트라이커 게일)(기운)', 'Spirit Crystal (Striker Gale) (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17064, '전사의 인장 (타이탄: 락)(기운)', 'Warrior\'s Seal (Titan: Rock) (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17065, '전사의 인장 (타이탄: 매직)(기운)', 'Warrior\'s Seal (Titan: Magic) (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17066, '전사의 인장 (타이탄: 블릿)(기운)', 'Warrior\'s Seal (Titan: Bullet) (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17067, '정령의 수정 (허리케인)(기운)', 'Spirit Crystal (Hurricane) (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17068, '\\aE기술서 (카운터 배리어:베테랑)(기운)', 'Technical Book (Counter Barrier: Veteran) (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17069, '\\aE흑정령의 수정 (아머 브레이크:데스티니)(기운)', 'Black Spirit\'s Crystal (Armor Break: Destiny) (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17070, '\\aE전사의 인장 (데스페라도:앱솔루트)(기운)', 'Warrior\'s Seal (Desperado: Absolute) (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17091, '오리하루콘 단검(기운)', 'Oriharukon Dagger (Energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17092, '\\aF나이트발드의 양손검(기운)', 'Nightbald\'s Two-Handed Sword (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17093, '파괴의 장궁(기운)', 'Longbow of Destruction (Energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17094, '론드의 이도류(기운)', 'Londe\'s Dual Blade (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17095, '바포메트의 지팡이(기운)', 'Baphomet\'s Staff (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17096, '힘의 지팡이(기운)', 'Staff of Power (Energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17097, '마나의 지팡이(기운)', 'Staff of Mana (Energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17098, '얼음 여왕의 지팡이(기운)', 'Ice Queen\'s Staff (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17099, '데몬의 지팡이(기운)', 'Demon\'s Staff (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17100, '블러드서커(기운)', 'Blood Sucker (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17101, '극한의 체인소드(기운)', 'Extreme Chainsword (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17102, '냉한의 키링크(기운)', 'Cold Key Link (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17103, '데스나이트의 불검(기운)', 'Death Knight\'s Fire Sword (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17104, '커츠의 검(기운)', 'Kurtz\'s Sword (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17105, '제로스의 지팡이(기운)', 'Zeros\' Staff (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17106, '살기의 키링크(기운)', 'Key link to life (energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17121, '\\aF리치 로브(기운)', 'Rich Robe (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17122, '데스나이트의 갑옷(기운)', 'Death Knight\'s Armor (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17123, '흑장로의 로브(기운)', 'Black Elder\'s Robe (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17124, '커츠의 갑옷(기운)', 'Kurtz\'s Armor (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17125, '거대 여왕 개미의 금빛 날개(기운)', 'Golden wings (energy) of the giant queen ant', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17126, '거대 여왕 개미의 은빛 날개(기운)', 'Silver wings (energy) of the giant queen ant', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17127, '\\aF뱀파이어의 망토(기운)', 'Vampire\'s Cloak (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17128, '투명 망토(기운)', 'Invisibility Cloak (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17129, '신성한 보호 망토(기운)', 'Sacred Protective Cloak (Energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17130, '\\aF시어의 심안(기운)', 'Seer\'s Mind\'s Eye (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17131, '반역자의 방패(기운)', 'Traitor\'s Shield (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17132, '데스나이트의 부츠(기운)', 'Death Knight\'s Boots (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17133, '커츠의 부츠(기운)', 'Kurtz\'s Boots (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17134, '타락의 부츠(기운)', 'Boots of Corruption (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17135, '돌 장갑(기운)', 'Stone Gloves (Energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17136, '데스나이트의 장갑(기운)', 'Death Knight\'s Gloves (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17137, '커츠의 장갑(기운)', 'Kurtz\'s Gloves (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17138, '타락의 장갑(기운)', 'Gloves of Corruption (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17139, '\\aF머미로드의 왕관(기운)', 'Mommy Lord\'s Crown (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17140, '지휘관의 투구(기운)', 'Commander\'s Helmet (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17141, '데스나이트의 투구(기운)', 'Death Knight\'s Helmet (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17142, '발터자르의 모자(기운)', 'Balterzar\'s Hat (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17143, '카스파의 모자(기운)', 'Caspar\'s Hat (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17144, '메르키오르의 모자(기운)', 'Merchior\'s Hat (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17145, '세마의 모자(기운)', 'Sema\'s Hat (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17146, '커츠의 투구(기운)', 'Kurtz\'s Helmet (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17147, '마법방어 각반(기운)', 'Magic Defense Gaiters (Energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17148, '흑장로의 샌달(기운)', 'Black Elder\'s Sandals (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17149, '혼돈의 투구(기운)', 'Helmet of Chaos (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17150, '실프의 티셔츠(기운)', 'Sylph\'s T-shirt (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17151, '신성한 마법 방어 투구(기운)', 'Sacred Magic Defense Helmet (Energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17152, '\\aF아이리스의 부츠(기운)', 'Iris\' Boots (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17153, '\\aF머미로드의 장갑(기운)', 'Mummy Lord\'s Gloves (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17154, '\\aF쿠거의 가더(기운)', 'Cougar\'s Guarder (Aura)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17155, '\\aF우그누스의 가더(기운)', 'Ugnus\'s Guarder (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17156, '\\aF나이트발드의 각반(기운)', 'Nightbald\'s Gaiters (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17157, '\\aF아이리스의 각반(기운)', 'AIris\' Gaiters (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17158, '\\aF뱀파이어의 각반(기운)', 'Vampire\'s Gaiters (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17159, '\\aF격분의 장갑(기운)', 'Rage Gloves (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17161, '도펠겡어 보스의 목걸이(기운)', 'Doppelg?nger Boss\'s Necklace (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17162, '투사의 목걸이(기운)', 'Fighter\'s Necklace (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17163, '현자의 목걸이(기운)', 'Sage\'s Necklace (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17164, '빛나는 사이하의 목걸이(기운)', 'Shiny Saiha\'s Necklace (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17165, '오림의 목걸이(기운)', 'Orim\'s Necklace (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17166, '도펠겡어 보스의 왼쪽 반지(기운)', 'Doppelg?nger Boss\' Left Ring (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17167, '도펠겡어 보스의 오른쪽 반지(기운)', 'Doppelg?nger Boss\'s Right Ring (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17168, '라이아의 반지(기운)', 'Laia\'s Ring (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17169, '신성한 일격의 반지(기운)', 'Ring of Holy Strike (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17170, '\\aF제니스의 반지(기운)', 'Zenith\'s Ring (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17171, '마왕의 반지(기운)', 'Devil\'s Ring (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17172, '기백의 반지(기운)', 'Ring of Spirit (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17173, '세마의 반지(기운)', 'Sema\'s Ring (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17174, '지식의 반지(기운)', 'Ring of Knowledge (Energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17175, '완력의 반지(기운)', 'Ring of strength (energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17176, '민첩의 반지(기운)', 'Ring of Agility (Energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17177, '에이션트 자이언트의 반지(기운)', 'Ancient Giant\'s Ring (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17178, '크로노스의 벨트(기운)', 'Kronos\' Belt (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17179, '타이탄의 벨트(기운)', 'Titan\'s Belt (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17180, '\\aF단풍 반지(기운)', 'Maple Ring (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17181, '일격의 반지(기운)', 'Ring of Strike (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17182, '\\aF사신의 반지(기운)', 'Shinigami\'s Ring (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17183, '\\aF리치의 반지(기운)', 'Rich\'s Ring (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17184, '사신의 사념 조각(기운)', 'Shinigami\'s Thought Piece (Energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17185, '전설 무기 제작 비법서(기운)', 'Legendary Weapon Crafting Secret Book (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17186, '용의 심장(기운)', 'Dragon\'s Heart (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17187, '봉인된 오만의 탑 1층 이동 부적(기운)', 'Sealed Tower of Arrogance 1st floor movement talisman (energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17188, '봉인된 오만의 탑 2층 이동 부적(기운)', 'Sealed Tower of Arrogance 2nd floor movement talisman (energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17189, '봉인된 오만의 탑 3층 이동 부적(기운)', 'Sealed Tower of Arrogance 3rd floor movement talisman (energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17190, '봉인된 오만의 탑 4층 이동 부적(기운)', 'Sealed Tower of Arrogance 4th floor movement talisman (energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17191, '봉인된 오만의 탑 5층 이동 부적(기운)', 'Sealed Tower of Arrogance 5th floor movement talisman (energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17192, '봉인된 오만의 탑 6층 이동 부적(기운)', 'Sealed Tower of Arrogance 6th floor movement talisman (energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17193, '봉인된 오만의 탑 7층 이동 부적(기운)', 'Sealed Tower of Arrogance 7th floor movement talisman (energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17194, '봉인된 오만의 탑 8층 이동 부적(기운)', 'Sealed Tower of Arrogance 8th floor movement talisman (energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17195, '봉인된 오만의 탑 9층 이동 부적(기운)', 'Sealed Tower of Arrogance 9th floor movement talisman (energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17196, '봉인된 오만의 탑 10층 이동 부적(기운)', 'Sealed Tower of Arrogance 10th floor movement talisman (energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17197, '안타라스의 숨결(기운)', 'Antaras\' Breath (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17198, '발라카스의 숨결(기운)', 'Breath of Balakas (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17199, '파푸리온의 숨결(기운)', 'Pafurion\'s Breath (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 17200, '린드비오르의 숨결(기운)', 'Lindvior\'s Breath (Energy)', 0, 'true'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 25131, '하딘의 수정구(기운)', 'Hardin\'s Crystal Ball (Energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 25132, '오림의 수정구(기운)', 'Orim\'s Crystal Ball (Energy)', 0, 'false'),
(17054, '생명의 나뭇잎', 'Leaf of Life', 25133, '\\aH사신의 숨결(기운)', 'Reaper\'s Breath (Energy)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25944, '\\aE마법서 (디스인티그레이트)(소생)', 'Spellbook (Disintegrate) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25945, '\\aE기술서 (카운터 배리어)(소생)', 'Technical Book (Counter Barrier) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25946, '\\aE정령의 수정 (소울 오브 프레임)(소생)', 'Spirit Crystal (Soul of Frame) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25947, '\\aE흑정령의 수정 (아머 브레이크)(소생)', 'Black Spirit\'s Crystal (Armor Break) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25948, '\\aE전사의 인장 (데스페라도)(소생)', 'Warrior\'s Seal (Desperado) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25949, '마법서 (미티어 스트라이크)(소생)', 'Spell Book (Meteor Strike) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25950, '전사의 인장 (타이탄: 락)(소생)', 'Warrior\'s Seal (Titan: Rock) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25951, '전사의 인장 (타이탄: 매직)(소생)', 'Warrior\'s Seal (Titan: Magic)(Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25952, '전사의 인장 (타이탄: 블릿)(소생)', 'Warrior\'s Seal (Titan: Bullet) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25953, '정령의 수정 (허리케인)(소생)', 'Spirit Crystal (Hurricane) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25954, '\\aE기술서 (카운터 배리어:베테랑)(소생)', 'Technical Book (Counter Barrier: Veteran) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25955, '\\aE흑정령의 수정 (아머 브레이크:데스티니)(소생)', 'Black Spirit\'s Crystal (Armor Break: Destiny) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25956, '\\aE전사의 인장 (데스페라도:앱솔루트)(소생)', 'Warrior\'s Seal (Desperado: Absolute) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25957, '\\aE정령의 수정 (인페르노)(소생)', 'Spirit Crystal (Inferno) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25958, '\\aE마법서 (엠파이어)(소생)', 'Spellbook (Empire) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25959, '\\aE검사의 서 (저지먼트)(소생)', 'Swordsman\'s Book (Judgement)(Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25960, '\\aE검사의 서 (팬텀:리퍼)(소생)', 'Swordsman\'s Book (Phantom: Reaper) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25961, '\\aH검사의 서 (팬텀:데스)(소생)', '\\aHSwordsman\'s Book (Phantom:Death)(Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25962, '\\aE검사의 서 (패러독스)(소생)', 'Swordsman\'s Book (Paradox) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25963, '\\aE검사의 서 (서바이브)(소생)', 'Swordsman\'s Book (Survive)(Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25964, '\\aE검사의 서 (판테라:쇼크)(소생)', 'Swordsman\'s Book (Pantera: Shock) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25965, '마법서 (콜 클랜 어드밴스)(소생)', 'Spell Book (Call Clan Advance) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25966, '정령의 수정 (리버레이션)(소생)', 'Spirit Crystal (Liberation) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25967, '\\aE정령의 수정 (스트라이커 게일:샷)(소생)', 'Spirit Crystal (Striker Gale: Shot) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25968, '마법서 (메디테이션: 비욘드)(소생)', 'Spellbook (Meditation: Beyond) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25969, '마법서 (매스 이뮨 투 함)(소생)', 'Spell Book (Mass Immune Throw) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25970, '흑정령의 수정 (무빙 악셀레이션: 맥시멈)(소생)', 'Black Spirit\'s Crystal (Moving Acceleration: Maximum) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25971, '흑정령의 수정 (쉐도우 아머: 데스티니)(소생)', 'Black Spirit\'s Crystal (Shadow Armor: Destiny) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25972, '기억의 수정 (본 브레이크: 래스트)(소생)', 'Memory Crystal (Bone Break: Last) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25973, '전사의 인장 (버서크)(소생)', 'Warrior\'s Seal (Berserk) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25975, '오리하루콘 단검(소생)', 'Oriharukon Dagger (Revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 25976, '\\aF나이트발드의 양손검(소생)', 'Nightbald\'s Two-Handed Sword (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25977, '론드의 이도류(소생)', 'Londe\'s dual sword style (revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25978, '바포메트의 지팡이(소생)', 'Baphomet\'s Staff (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25979, '얼음 여왕의 지팡이(소생)', 'Ice Queen\'s Staff (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25980, '데몬의 지팡이(소생)', 'Demon\'s Staff (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25981, '블러드서커(소생)', 'Bloodsucker (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25982, '극한의 체인소드(소생)', 'Extreme Chainsword (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25983, '냉한의 키링크(소생)', 'Cold Key Link (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25984, '데스나이트의 불검(소생)', 'Death Knight\'s Fire Sword (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25985, '커츠의 검(소생)', 'Kurtz\'s Sword (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25986, '제로스의 지팡이(소생)', 'Zeros\' Staff (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25987, '살기의 키링크(소생)', 'Key link of survival (revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 25988, '\\aF듀크데필의 검(소생)', 'Duke Defil\'s Sword (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26000, '\\aF리치 로브(소생)', 'Rich Robe (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26001, '데스나이트의 갑옷(소생)', 'Death Knight\'s Armor (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26002, '흑장로의 로브(소생)', 'Black Elder\'s Robe (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26003, '커츠의 갑옷(소생)', 'Kurtz\'s Armor (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26004, '거대 여왕 개미의 금빛 날개(소생)', 'Golden wings of the giant queen ant (revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26005, '거대 여왕 개미의 은빛 날개(소생)', 'Silver Wings of the Giant Queen Ant (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26006, '\\aF뱀파이어의 망토(소생)', 'Vampire\'s Cloak (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26007, '투명 망토(소생)', 'Invisibility Cloak (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26008, '신성한 보호 망토(소생)', 'Holy Protective Cloak (Revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26009, '\\aF시어의 심안(소생)', 'Seer\'s Mind\'s Eye (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26010, '반역자의 방패(소생)', 'Traitor\'s Shield (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26011, '데스나이트의 부츠(소생)', 'Death Knight\'s Boots (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26012, '커츠의 부츠(소생)', 'Kurtz\'s Boots (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26013, '타락의 부츠(소생)', 'Boots of Corruption (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26014, '돌 장갑(소생)', 'Stone Gloves (Revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26015, '데스나이트의 장갑(소생)', 'Death Knight\'s Gloves (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26016, '커츠의 장갑(소생)', 'Kurtz\'s Gloves (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26017, '타락의 장갑(소생)', 'Gloves of Corruption (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26018, '\\aF머미로드의 왕관(소생)', 'Mummy Lord\'s Crown (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26019, '지휘관의 투구(소생)', 'Commander\'s Helmet (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26020, '데스나이트의 투구(소생)', 'Death Knight\'s Helmet (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26021, '발터자르의 모자(소생)', 'Balterzar\'s Hat (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26022, '카스파의 모자(소생)', 'Caspar\'s Hat (Revived)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26023, '메르키오르의 모자(소생)', 'Merchior\'s Hat (Revived)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26024, '세마의 모자(소생)', 'Sema\'s Hat (Revived)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26025, '커츠의 투구(소생)', 'Kurtz\'s Helmet (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26026, '마법방어 각반(소생)', 'Magic Defense Gaiters (Revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26027, '흑장로의 샌달(소생)', 'Black Elder\'s Sandals (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26028, '혼돈의 투구(소생)', 'Helmet of Chaos (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26029, '실프의 티셔츠(소생)', 'Sylph\'s T-shirt (Revived)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26030, '신성한 마법 방어 투구(소생)', 'Sacred Magic Defense Helmet (Revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26031, '\\aF아이리스의 부츠(소생)', 'Iris\' Boots (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26032, '\\aF머미로드의 장갑(소생)', 'Mummylord\'s Gloves (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26033, '\\aF쿠거의 가더(소생)', 'Cougar\'s Guarder (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26034, '\\aF우그누스의 가더(소생)', 'Ugnus\'s Guarder (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26035, '\\aF나이트발드의 각반(소생)', 'Nightbald\'s Gaiters (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26036, '\\aF아이리스의 각반(소생)', 'Iris\' Gaiters (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26037, '\\aF뱀파이어의 각반(소생)', 'Vampire\'s Gaiters (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26038, '\\aF격분의 장갑(소생)', 'Rage Gloves (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26039, '\\aF에르자베의 왕관(소생)', 'Erzabe\'s Crown (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26061, '도펠겡어 보스의 목걸이(소생)', 'Doppelg?nger Boss\'s Necklace (Revived)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26062, '투사의 목걸이(소생)', 'Fighter\'s Necklace (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26063, '현자의 목걸이(소생)', 'Sage\'s Necklace (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26064, '빛나는 사이하의 목걸이(소생)', 'Shining Saiha\'s Necklace (Revived)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26065, '오림의 목걸이(소생)', 'Orim\'s Necklace (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26066, '도펠겡어 보스의 왼쪽 반지(소생)', 'Doppelg?nger Boss\'s Left Ring (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26067, '도펠겡어 보스의 오른쪽 반지(소생)', 'Doppelg?nger Boss\'s Right Ring (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26068, '라이아의 반지(소생)', 'Laia\'s Ring (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26069, '신성한 일격의 반지(소생)', 'Ring of Holy Strike (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26070, '\\aF제니스의 반지(소생)', 'Zenith\'s Ring (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26071, '마왕의 반지(소생)', 'The Devil\'s Ring (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26072, '기백의 반지(소생)', 'Ring of Spirit (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26073, '세마의 반지(소생)', 'Sema\'s Ring (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26074, '지식의 반지(소생)', 'Ring of Knowledge (Revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26075, '완력의 반지(소생)', 'Ring of Strength (Revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26076, '민첩의 반지(소생)', 'Ring of Agility (Revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26077, '에이션트 자이언트의 반지(소생)', 'Ancient Giant\'s Ring (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26078, '크로노스의 벨트(소생)', 'Kronos\' Belt (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26079, '타이탄의 벨트(소생)', 'Titan\'s Belt (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26080, '\\aF단풍 반지(소생)', 'Maple Ring (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26081, '일격의 반지(소생)', 'Ring of Strike (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26082, '\\aF사신의 반지(소생)', 'Shinigami\'s Ring (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26083, '\\aF리치의 반지(소생)', 'Rich\'s Ring (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26084, '\\aF에르자베의 목걸이(소생)', 'Erzabe\'s Necklace (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26101, '사신의 사념 조각(소생)', 'Sculpture of Death\'s Thoughts (Revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26102, '전설 무기 제작 비법서(소생)', 'Legendary Weapon Crafting Secret Book (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26103, '용의 심장(소생)', 'Heart of the Dragon (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26104, '봉인된 오만의 탑 1층 이동 부적(소생)', 'Sealed Tower of Arrogance 1st floor movement talisman (revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26105, '봉인된 오만의 탑 2층 이동 부적(소생)', 'Sealed Tower of Arrogance 2nd floor movement talisman (revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26106, '봉인된 오만의 탑 3층 이동 부적(소생)', 'Sealed Tower of Arrogance 3rd floor movement talisman (revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26107, '봉인된 오만의 탑 4층 이동 부적(소생)', 'Sealed Tower of Arrogance 4th floor movement talisman (revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26108, '봉인된 오만의 탑 5층 이동 부적(소생)', 'Sealed Tower of Arrogance 5th floor movement talisman (revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26109, '봉인된 오만의 탑 6층 이동 부적(소생)', 'Sealed Tower of Arrogance 6th floor movement talisman (revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26110, '봉인된 오만의 탑 7층 이동 부적(소생)', 'Sealed Tower of Arrogance 7th floor movement talisman (revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26111, '봉인된 오만의 탑 8층 이동 부적(소생)', 'Sealed Tower of Arrogance 8th floor movement talisman (revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26112, '봉인된 오만의 탑 9층 이동 부적(소생)', 'Sealed Tower of Arrogance 9th Floor Movement Amulet (Revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26113, '봉인된 오만의 탑 10층 이동 부적(소생)', 'Sealed Tower of Arrogance 10th floor movement talisman (revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26114, '안타라스의 숨결(소생)', 'Breath of Antharas (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26115, '발라카스의 숨결(소생)', 'Breath of Balakas (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26116, '파푸리온의 숨결(소생)', 'Breath of Papurion (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26117, '린드비오르의 숨결(소생)', 'Lindvior\'s Breath (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 26118, '하딘의 수정구(소생)', 'Hardin\'s Crystal Ball (Revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26119, '오림의 수정구(소생)', 'Orim\'s Crystal Ball (Revival)', 0, 'false'),
(25940, '소생 주문서', 'Resurrection Scroll', 26120, '\\aH사신의 숨결(소생)', 'Reaper\'s Breath (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 28578, '지휘관의 창(소생)', 'Commander\'s Spear (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 28616, '창술서 (닷지 브레이크)(소생)', 'Language Book (Dodge Break) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 28617, '창술서 (인크리즈 레인지)(소생)', 'Spear Book (Increase Range) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 28618, '창술서 (리커버리)(소생)', 'Spear Book (Recovery)(Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 28619, '창술서 (마엘스트롬)(소생)', 'Book of Spearmanship (Maelstrom) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 28620, '\\aE창술서 (크루얼:컨빅션)(소생)', 'Spear Book (Crewel: Conviction) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 28621, '\\aH창술서 (프레셔:데스 리콜)(소생)', 'Spear (Pressure: Death Recall) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29128, '\\aE마법서 (디스인티그레이트:네메시스)(소생)', 'Spell Book (Disintegrate: Nemesis) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29129, '\\aE마법서 (홀리 워크:에볼루션)(소생)', 'Spellbook (Holy Work: Evolution) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29130, '\\aE마법서 (에테리얼 서클)(소생)', 'Spellbook (Ethereal Circle) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29131, '\\aE마법서 (디바인 프로텍션)(소생)', 'Spellbook (Divine Protection) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29162, '리치의 벨트(소생)', 'Lich\'s Belt (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29252, '\\aE마법서 (그레이트 서먼 몬스터)(소생)', 'Spellbook (Great Summon Monster) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29261, '\\aF루운3세의 부츠(소생)', 'Ruun III\'s Boots (Revived)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29262, '\\aF귀신의 망토(소생)', 'Ghost\'s Cloak (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29352, '\\aE검사의 서 (팬텀:레퀴엠)(소생)', 'Swordsman\'s Book (Phantom: Requiem) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29644, '\\aE전사의 인장 (타이탄: 비스트)(소생)', 'Warrior\'s Seal (Titan: Beast) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29645, '\\aE전사의 인장 (템페스트)(소생)', 'Warrior\'s Seal (Tempest) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29646, '전사의 인장 (토마호크: 헌터)(소생)', 'Warrior\'s Seal (Tomahawk: Hunter) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29653, '\\aE정령의 수정 (비전 텔레포트)(소생)', 'Spirit Crystal (Vision Teleport) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29654, '\\aE정령의 수정 (트리플 애로우: 부스트)(소생)', 'Spirit Crystal (Triple Arrow: Boost)(Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29655, '\\aE정령의 수정 (파인 사이트)(소생)', 'Spirit Crystal (Fine Sight) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29658, '\\aE흑정령의 수정 (쉐도우 스탭: 체이서)(소생)', 'Black Spirit\'s Crystal (Shadow Staff: Chaser) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29659, '\\aE흑정령의 수정 (블라인드 하이딩: 어쌔신)(소생)', 'Black Spirit\'s Crystal (Blind Hiding: Assassin) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29702, '\\aE마법서 (엠파이어:오버로드)(소생)', 'Spellbook (Empire: Overlord) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29705, '\\aE기술서 (쇼크 어택)(소생)', 'Technical Book (Shock Attack) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29707, '\\aE기술서 (카운터 배리어:마스터)(소생)', 'Technical Book (Counter Barrier: Master) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29709, '\\aE기술서 (레이징 웨폰)(소생)', 'Technical Book (Razing Weapon) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29711, '\\aE정령의 수정 (소울 배리어:아머)(소생)', 'Spirit Crystal (Soul Barrier: Armor) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29713, '\\aE정령의 수정 (버닝 샷)(소생)', 'Spirit\'s Crystal (Burning Shot) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29831, '\\aE용기사의 서판 (포우 슬레이어:브레이브)(소생)', 'Dragon Knight\'s Tablet (Foe Slayer: Brave) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 29915, '정화의 부츠(소생)', 'Boots of Purification (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31100, '\\aJ기억의 수정 (인스네어) (소생)', 'Memory Crystal (Insnare) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31101, '\\aH기억의 수정 (오시리스) (소생)', 'Crystal of Memory (Osiris) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31705, '\\aF마법서 (프라임) (소생)', 'Magic Book (Prime) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31706, '\\aF기술서 (포스 스턴) (소생)', 'Technique (Force Stun) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31707, '\\aF정령의 수정 (글로리 어스) (소생)', 'Spirit\'s Crystal (Glorious Earth) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31708, '\\aF마법서 (이터니티) (소생)', 'Spell Book (Eternity) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31709, '\\aF흑정령의 수정 (어벤저) (소생)', 'Black Spirit\'s Crystal (Avenger) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31710, '\\aF용기사의 서판 (할파스) (소생)', 'Dragon Knight\'s Tablet (Halfas) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31711, '\\aF기억의 수정 (포텐셜) (소생)', 'Memory Crystal (Potential) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31712, '\\aF전사의 인장 (데몰리션) (소생)', 'Warrior\'s Seal (Demolition) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31860, '\\aJ마법서 (브레이브 유니언) (소생)', 'Magic Book (Brave Union) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31861, '\\aJ마법서 (타이런트: 엑스큐션) (소생)', 'Magic Book (Tyrant: Execution) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31862, '\\aH마법서 (컨쿼러) (소생)', 'Magic Book (Conqueror) (Revival)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31883, '마법서 (브레이브 유니언) (소생) (각인)', 'Spell Book (Brave Union) (Revival) (Imprint)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31884, '마법서 (타이런트: 엑스큐션) (소생) (각인)', 'Spellbook (Tyrant: Execution) (Revival) (Imprint)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31885, '기술서 (쇼크 어택) (소생) (각인)', 'Technical Book (Shock Attack) (Revival) (Imprint)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31886, '기술서 (레이징 웨폰) (소생) (각인)', 'Technical Book (Razing Weapon) (Revival) (Engraving)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31887, '마법서 (홀리 워크: 에볼루션) (소생) (각인)', 'Spell Book (Holy Work: Evolution) (Revival) (Imprint)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31888, '마법서 (매스 이뮨 투 함) (소생) (각인)', 'Spell Book (Mass Immune Throw) (Revival) (Imprint)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31889, '기억의 수정 (인스네어) (소생) (각인)', 'Crystal of Memory (Ensnare) (Revival) (Imprint)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31890, '전사의 인장 (데스페라도: 앱솔루트) (소생) (각인)', 'Warrior\'s Seal (Desperado: Absolute) (Revival) (Imprint)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31891, '검사의 서 (팬텀: 리퍼) (소생) (각인)', 'Swordsman\'s Book (Phantom: Reaper) (Revival) (Imprint)', 0, 'true'),
(25940, '소생 주문서', 'Resurrection Scroll', 31892, '검사의 서 (팬텀: 레퀴엠) (소생) (각인)', 'Swordsman\'s Book (Phantom: Requiem) (Revival) (Imprint)', 0, 'true');
