
-- --------------------------------------------------------

--
-- Table structure for table `item_ment`
--

CREATE TABLE `item_ment` (
  `itemId` int(10) NOT NULL DEFAULT 0,
  `itemName` varchar(50) DEFAULT NULL,
  `desc_kr` varchar(50) NOT NULL,
  `mentType` enum('treasurebox','craft','drop','pickup') NOT NULL DEFAULT 'pickup'
) ENGINE=InnoDB DEFAULT CHARSET=euckr COLLATE=euckr_korean_ci;

--
-- Dumping data for table `item_ment`
--

INSERT INTO `item_ment` (`itemId`, `itemName`, `desc_kr`, `mentType`) VALUES
(12, '\\aHWind Blade Dagger', '바람칼날의 단검', 'craft'),
(45, 'Porsche\'s Sword', '포르세의 검', 'craft'),
(54, 'Kurtz\'s Sword', '커츠의 검', 'craft'),
(58, 'Death Knight\'s Fire Sword', '데스나이트의 불검', 'craft'),
(61, '\\aHFidelity Execution Sword', '진명황의 집행검', 'craft'),
(86, '\\aHRed Shadow Edoryu', '붉은 그림자의 이도류', 'craft'),
(134, '\\aHCrystalline Staff', '수정결정체 지팡이', 'craft'),
(745, 'Magic Doll: Demon', '마법인형: 데몬', 'treasurebox'),
(746, 'Magic Doll: Death Knight', '마법인형: 데스나이트', 'treasurebox'),
(752, 'Magic Doll: Corruption', '마법인형: 타락', 'treasurebox'),
(1121, '\\aFKnight Vald Sword', '나이트발드의 양손검', 'craft'),
(1136, '\\f4Nightmare Longbow', '악몽의 장궁', 'craft'),
(2014, '\\aEBook of Fencer (Judgement)', '검사의 서 (저지먼트)', 'treasurebox'),
(2014, '\\aEBook of Fencer (Judgement)', '검사의 서 (저지먼트)', 'craft'),
(2022, '\\aEBook of Fencer (Survive)', '검사의 서 (서바이브)', 'treasurebox'),
(2022, '\\aEBook of Fencer (Survive)', '검사의 서 (서바이브)', 'craft'),
(2024, '\\aEBook of Fencer (Paradox)', '검사의 서 (패러독스)', 'treasurebox'),
(2024, '\\aEBook of Fencer (Paradox)', '검사의 서 (패러독스)', 'craft'),
(2025, '\\aJSwordman Book (Phantom: Reaper)', '검사의 서 (팬텀:리퍼)', 'treasurebox'),
(2025, '\\aJSwordman Book (Phantom: Reaper)', '검사의 서 (팬텀:리퍼)', 'craft'),
(2026, '\\aHSwordman Book (Pantera: Shock)', '검사의 서 (판테라:쇼크)', 'treasurebox'),
(2026, '\\aHSwordman Book (Pantera: Shock)', '검사의 서 (판테라:쇼크)', 'craft'),
(2027, '\\aGSwordman Book (Phantom: Death)', '검사의 서 (팬텀:데스)', 'treasurebox'),
(2027, '\\aGSwordman Book (Phantom: Death)', '검사의 서 (팬텀:데스)', 'craft'),
(2029, '\\aEBook of Fencer (Phantom: Requiem)', '검사의 서 (팬텀:레퀴엠)', 'treasurebox'),
(2029, '\\aEBook of Fencer (Phantom: Requiem)', '검사의 서 (팬텀:레퀴엠)', 'craft'),
(3016, '\\aFSpearbook (Cruel: Conviction)', '창술서 (크루얼:컨빅션)', 'treasurebox'),
(3016, '\\aFSpearbook (Cruel: Conviction)', '창술서 (크루얼:컨빅션)', 'craft'),
(3017, '\\aGSpearbook (Pressure: Death Recall)', '창술서 (프레셔:데스 리콜)', 'treasurebox'),
(3017, '\\aGSpearbook (Pressure: Death Recall)', '창술서 (프레셔:데스 리콜)', 'craft'),
(3018, 'Spear Technique (Dodge Break)', '창술서 (닷지 브레이크)', 'treasurebox'),
(3018, 'Spear Technique (Dodge Break)', '창술서 (닷지 브레이크)', 'craft'),
(3019, 'Spear Technique (Maelstrom)', '창술서 (마엘스트롬)', 'treasurebox'),
(3019, 'Spear Technique (Maelstrom)', '창술서 (마엘스트롬)', 'craft'),
(5559, '\\aEDark Spirit Crystal(Armor Break)', '흑정령의 수정 (아머 브레이크)', 'treasurebox'),
(5559, '\\aEDark Spirit Crystal(Armor Break)', '흑정령의 수정 (아머 브레이크)', 'craft'),
(5603, '\\aETechnical Book(Counter Barrier: Veteran)', '기술서 (카운터 배리어:베테랑)', 'treasurebox'),
(5603, '\\aETechnical Book(Counter Barrier: Veteran)', '기술서 (카운터 배리어:베테랑)', 'craft'),
(5606, '\\aEDark Spirit Crystal (Armor Break: Destiny)', '흑정령의 수정 (아머 브레이크:데스티니)', 'treasurebox'),
(5606, '\\aEDark Spirit Crystal (Armor Break: Destiny)', '흑정령의 수정 (아머 브레이크:데스티니)', 'craft'),
(5607, '\\aJWarrior Seal (Desperado: Absolute)', '전사의 인장 (데스페라도:앱솔루트)', 'treasurebox'),
(5607, '\\aJWarrior Seal (Desperado: Absolute)', '전사의 인장 (데스페라도:앱솔루트)', 'craft'),
(20017, '\\aFCrown of Mummy Lord', '머미로드의 왕관', 'craft'),
(20049, 'Ant Queen Golden Wings', '거대 여왕 개미의 금빛 날개', 'craft'),
(20050, 'Ant Queen Silver Wings', '거대 여왕 개미의 은빛 날개', 'craft'),
(20077, 'Cloak of Invisibility', '투명 망토', 'craft'),
(20079, 'Vampire Cloak', '뱀파이어의 망토', 'craft'),
(20107, '\\aFLich Robe', '리치 로브', 'craft'),
(20271, 'Amulet of Glowing Saiha', '빛나는 사이하의 목걸이', 'craft'),
(20272, 'Ring of Strike', '일격의 반지', 'craft'),
(20279, 'Ring of Laia', '라이아의 반지', 'craft'),
(20298, '\\aFRing of Zenith', '제니스의 반지', 'craft'),
(20314, 'Ring of Ancient Giant', '에이션트 자이언트의 반지', 'craft'),
(20320, 'Titan Belt', '타이탄의 벨트', 'craft'),
(22008, 'Ring of Demon King', '마왕의 반지', 'craft'),
(22009, 'Ring of Spirit', '기백의 반지', 'craft'),
(22214, '\\aFSeer\'s Depths', '시어의 심안', 'craft'),
(22263, 'Rebel Shield', '반역자의 방패', 'craft'),
(22360, 'Helm of the Commander', '지휘관의 투구', 'craft'),
(23000, '\\aHHalpas Dark Plate Mail', '할파스의 완력', 'craft'),
(23001, '\\aHHalpas Dark Scale Mail', '할파스의 예지력', 'craft'),
(23002, '\\aHHalpas Dark Robe', '할파스의 마력', 'craft'),
(23003, '\\aEBreath of Halpas', '\\aE할파스의 숨결', 'treasurebox'),
(23003, '\\aEBreath of Halpas', '\\aE할파스의 숨결', 'craft'),
(23010, '\\aFAmulet of Ershabe', '에르자베의 목걸이', 'craft'),
(23011, '\\aFCrown of Ershabe', '에르자베의 왕관', 'craft'),
(31126, 'Magic Doll: Baphomet', '마법인형: 바포메트', 'treasurebox'),
(31127, 'Magic Doll: Ice Queen', '마법인형: 얼음여왕', 'treasurebox'),
(31128, 'Magic Doll: Kurtz', '마법인형: 커츠', 'treasurebox'),
(31172, 'Legendary Weapon Crafting Secret Book', '전설 무기 제작 비법서', 'craft'),
(40219, 'Spellbook (Meteor Strike)', '마법서 (미티어 스트라이크)', 'craft'),
(40222, '\\aESpellbook (Desintegrate)', '마법서 (디스인티그레이트)', 'treasurebox'),
(40222, '\\aESpellbook (Desintegrate)', '마법서 (디스인티그레이트)', 'craft'),
(40280, '\\aFBlack Black Spirit Crystal (Avenger)', '흑정령의 수정 (어벤저)', 'drop'),
(40282, 'Spirit Crystal (Hurricane)', '정령의 수정 (허리케인)', 'treasurebox'),
(40282, 'Spirit Crystal (Hurricane)', '정령의 수정 (허리케인)', 'craft'),
(40284, '\\aESpirit Crystal (Inferno)', '정령의 수정 (인페르노)', 'treasurebox'),
(40284, '\\aESpirit Crystal (Inferno)', '정령의 수정 (인페르노)', 'craft'),
(40285, '\\aeSpellbook (Empire)', '마법서 (엠파이어)', 'craft'),
(40286, '\\aFSpirit Crystal (Glory Earth)', '정령의 수정 (글로리 어스)', 'drop'),
(40287, '\\aFMagic Book (Prime)', '마법서 (프라임)', 'drop'),
(40288, 'Spirit Crystal (Magic Shield)', '정령의 수정 (매직 실드)', 'treasurebox'),
(40288, 'Spirit Crystal (Magic Shield)', '정령의 수정 (매직 실드)', 'craft'),
(40290, 'Spellbook (Call Clan Advance)', '마법서 (콜 클랜 어드밴스)', 'treasurebox'),
(40290, 'Spellbook (Call Clan Advance)', '마법서 (콜 클랜 어드밴스)', 'craft'),
(40292, '\\aESpirit Crystal(Striker Gail: Shot)', '정령의 수정 (스트라이커 게일:샷)', 'treasurebox'),
(40292, '\\aESpirit Crystal(Striker Gail: Shot)', '정령의 수정 (스트라이커 게일:샷)', 'craft'),
(40293, '\\aeSpellbook (Empire: Overlord)', '마법서 (엠파이어:오버로드)', 'treasurebox'),
(40293, '\\aeSpellbook (Empire: Overlord)', '마법서 (엠파이어:오버로드)', 'craft'),
(40295, '\\aESpirit Crystal (Burning Shot)', '정령의 수정 (버닝 샷)', 'treasurebox'),
(40295, '\\aESpirit Crystal (Burning Shot)', '정령의 수정 (버닝 샷)', 'craft'),
(40346, 'Heart of Antharas', '안타라스의 숨결', 'craft'),
(40354, 'Heart of Valakas', '발라카스의 숨결', 'craft'),
(40362, 'Heart of Fafurion', '파푸리온의 숨결', 'craft'),
(40370, 'Heart of Lindvior', '린드비오르의 숨결', 'craft'),
(41148, '\\aETechnical Book (Counter Barrier)', '기술서 (카운터 배리어)', 'treasurebox'),
(41148, '\\aETechnical Book (Counter Barrier)', '기술서 (카운터 배리어)', 'craft'),
(41149, '\\aESpirit Crystal (Flame Soul)', '정령의 수정 (소울 오브 프레임)', 'treasurebox'),
(41149, '\\aESpirit Crystal (Flame Soul)', '정령의 수정 (소울 오브 프레임)', 'craft'),
(41500, '\\aFMagic Book (Eternity)', '마법서 (이터니티)', 'drop'),
(42000, '\\aFTech Book (Force Stun)', '기술서 (포스 스턴)', 'drop'),
(42032, '\\aJTech Book (Shock Attack)', '기술서 (쇼크 어택)', 'treasurebox'),
(42032, '\\aJTech Book (Shock Attack)', '기술서 (쇼크 어택)', 'craft'),
(42033, '\\aETechnical Book (Counter Barrier: Master)', '기술서 (카운터 배리어:마스터)', 'treasurebox'),
(42033, '\\aETechnical Book (Counter Barrier: Master)', '기술서 (카운터 배리어:마스터)', 'craft'),
(43010, 'Spellbook (Immune To Harm: Saint)', '마법서 (이뮨 투 함:세인트)', 'treasurebox'),
(43010, 'Spellbook (Immune To Harm: Saint)', '마법서 (이뮨 투 함:세인트)', 'craft'),
(43014, 'Spellbook (Mass Immune To Harm)', '마법서 (매스 이뮨 투 함)', 'treasurebox'),
(43014, 'Spellbook (Mass Immune To Harm)', '마법서 (매스 이뮨 투 함)', 'craft'),
(43016, 'Dark Spirit Crystal (Moving Acceleration: Maximum)', '흑정령의 수정 (무빙 악셀레이션: 맥시멈)', 'treasurebox'),
(43016, 'Dark Spirit Crystal (Moving Acceleration: Maximum)', '흑정령의 수정 (무빙 악셀레이션: 맥시멈)', 'craft'),
(43017, '\\aeSpellbook (Divine Protect)', '마법서 (디바인 프로텍션)', 'treasurebox'),
(43017, '\\aeSpellbook (Divine Protect)', '마법서 (디바인 프로텍션)', 'craft'),
(43018, '\\aHSpellbook (Disintegrate: Nemess)', '마법서 (디스인티그레이트:네메시스)', 'treasurebox'),
(43018, '\\aHSpellbook (Disintegrate: Nemess)', '마법서 (디스인티그레이트:네메시스)', 'craft'),
(93005, '\\aFBoots of Rune III', '루운3세의 부츠', 'treasurebox'),
(93005, '\\aFBoots of Rune III', '루운3세의 부츠', 'craft'),
(93006, '\\aFCloak of the devil', '귀신의 망토', 'treasurebox'),
(93006, '\\aFCloak of the devil', '귀신의 망토', 'craft'),
(93007, 'Boots of Purification', '정화의 부츠', 'treasurebox'),
(93007, 'Boots of Purification', '정화의 부츠', 'craft'),
(202003, 'Xeroth Staff', '제로스의 지팡이', 'craft'),
(202011, '\\aHGaias Wrath', '가이아의 격노', 'craft'),
(202012, '\\aHHyperions Despair', '히페리온의 절망', 'craft'),
(202013, '\\aHKronos Horror', '크로노스의 공포', 'craft'),
(202014, '\\aHTitans Wrath', '타이탄의 분노', 'craft'),
(202810, '\\aFDomination Ring', '\\aF변신 지배 반지', 'treasurebox'),
(202810, '\\aFDomination Ring', '변신 지배 반지', 'craft'),
(202811, 'Teleport Domination Ring', '순간이동 지배 반지', 'craft'),
(203006, 'Tempest Axe', '태풍의 도끼', 'craft'),
(203017, '\\f4Annihilator Chainsword', '섬멸자의 체인소드', 'craft'),
(203018, '\\aFRoaring Edoryu', '포효의 이도류', 'craft'),
(203035, 'Living Kiringku', '살기의 키링크', 'craft'),
(203041, '\\aHReaper Sword', '사신의 검', 'craft'),
(203042, '\\aGEinhasad Flash', '아인하사드의 섬광', 'craft'),
(203043, '\\aGJudgment of Gran Kain', '그랑카인의 심판', 'craft'),
(203044, '\\aFSword of Duke Defill', '듀크데필의 검', 'treasurebox'),
(203044, '\\aFSword of Duke Defill', '듀크데필의 검', 'craft'),
(203046, 'Commander Spear', '지휘관의 창', 'treasurebox'),
(203046, 'Commander Spear', '지휘관의 창', 'craft'),
(203049, '\\aHRulers Execution', '지배자의 처형', 'craft'),
(203050, '\\aFValakas Longsword', '발라카스의 장검', 'craft'),
(203051, '\\aFValakas Two-handed Sword', '발라카스의 양손검', 'craft'),
(203052, '\\aFFafurion Longbow', '파푸리온의 장궁', 'craft'),
(203053, '\\aFFafurion Edoryu', '파푸리온의 이도류', 'craft'),
(203054, '\\aFAntharas Axe', '안타라스의 도끼', 'craft'),
(203055, '\\aFAntharas Staff', '안타라스의 지팡이', 'craft'),
(203056, '\\aFLindvior Chainsword', '린드비오르의 체인소드', 'craft'),
(203057, '\\aFLindvior Kiringku', '린드비오르의 키링크', 'craft'),
(203058, '\\aGEva\'s Vow', '에바의 서약', 'craft'),
(203059, '\\aGAgony of Marble', '마프르의 고뇌', 'craft'),
(203060, '\\aGShilen\'s Determination', '실렌의 결의', 'craft'),
(203061, '\\aGSaiha\'s Tenacity', '사이하의 집념', 'craft'),
(203063, '\\aGGran Kain\'s Judgement', '그랑카인의 공포', 'craft'),
(203064, '\\aGDantes\' Trial', '\\aG단테스의 시련', 'craft'),
(203065, '\\aFValakas Spear', '\\aF발라카스의 창', 'craft'),
(203066, '\\aGTheia\'s Chaos', '\\aG테이아의 혼돈', 'craft'),
(210125, '\\aEWarrior Seal (Desperado)', '전사의 인장 (데스페라도)', 'treasurebox'),
(210125, '\\aEWarrior Seal (Desperado)', '전사의 인장 (데스페라도)', 'craft'),
(210130, 'Warrior Seal (Titan Lock)', '전사의 인장 (타이탄: 락)', 'treasurebox'),
(210130, 'Warrior Seal (Titan Lock)', '전사의 인장 (타이탄 락)', 'craft'),
(210131, 'Warrior Seal (Titan Blitz)', '전사의 인장 (타이탄: 블릿)', 'treasurebox'),
(210131, 'Warrior Seal (Titan Blitz)', '전사의 인장 (타이탄 블릿)', 'craft'),
(210132, 'Warrior Seal (Titan Magic)', '전사의 인장 (타이탄: 매직)', 'treasurebox'),
(210132, 'Warrior Seal (Titan Magic)', '전사의 인장 (타이탄 매직)', 'craft'),
(210135, '\\aGWarrior Seal (Tempest)', '전사의 인장 (템페스트)', 'craft'),
(210135, '\\aGWarrior Seal (Tempest)', '전사의 인장 (템페스트)', 'drop'),
(210136, '\\aHWarrior Seal (Titan: Beast)', '전사의 인장 (타이탄: 비스트)', 'treasurebox'),
(210136, '\\aHWarrior Seal (Titan: Beast)', '전사의 인장 (타이탄: 비스트)', 'craft'),
(210137, 'Warrior Seal (Tomahawk: Hunter)', '전사의 인장 (토마호크: 헌터)', 'treasurebox'),
(210137, 'Warrior Seal (Tomahawk: Hunter)', '전사의 인장 (토마호크: 헌터)', 'craft'),
(210150, '\\aJMemory Crystal (Insnaire)', '기억의 수정(인스네어)', 'treasurebox'),
(210150, '\\aJMemory Crystal (Insnaire)', '기억의 수정(인스네어)', 'craft'),
(210151, '\\aHMemory Crystal (Osiris)', '기억의 수정(오시리스)', 'treasurebox'),
(210151, '\\aHMemory Crystal (Osiris)', '기억의 수정(오시리스)', 'craft'),
(220010, '\\aFDragon Tablet (Halfas)', '용기사의 서판(할파스)', 'drop'),
(220050, '\\aFMemory Crystal (Potential)', '기억의 수정(포텐셜)', 'drop'),
(222304, 'Warrior\'s Necklace', '투사의 목걸이', 'craft'),
(222306, 'Amulet of Intelligence', '현자의 목걸이', 'craft'),
(222317, '\\aFEnraged Gloves', '격분의 장갑', 'craft'),
(400100, '\\aFBoots of Iris', '아이리스의 부츠', 'craft'),
(400101, '\\aFCougar Guarder', '쿠거의 가더', 'craft'),
(400102, '\\aFGuarder of Ugnus', '우그누스의 가더', 'craft'),
(400103, '\\aFNightvald\'s Gaiters', '나이트발드의 각반', 'craft'),
(400104, '\\aFIris Gaiters', '아이리스의 각반', 'craft'),
(400105, '\\aFVampire Gaiters', '뱀파이어의 각반', 'craft'),
(400106, '\\aFMummy Lord Gloves', '머미로드의 장갑', 'craft'),
(400107, '\\aFRing of the Grim Reaper', '사신의 반지', 'craft'),
(400108, '\\aFLich Ring', '리치의 반지', 'craft'),
(400109, '\\aHBreath of the Grim Reaper', '사신의 숨결', 'craft'),
(420100, 'Flame Box', '안타라스의 완력', 'craft'),
(420101, 'Arctic Extreme Frigid Box', '안타라스의 예지력', 'craft'),
(420102, 'Flash Light Box', '안타라스의 인내력', 'craft'),
(420103, 'Dimension Wand (Fire Ground)', '안타라스의 마력', 'craft'),
(420104, 'Dimension Wand (Meteor Strike)', '파푸리온의 완력', 'craft'),
(420105, 'Dimension Wand (Fire Storm)', '파푸리온의 예지력', 'craft'),
(420106, 'Dimension Wand (Blizzard)', '파푸리온의 인내력', 'craft'),
(420107, 'Dimension Wand (Ice Ridge)', '파푸리온의 마력', 'craft'),
(420108, 'Dimension Wand (Ice Meteor)', '린드비오르의 완력', 'craft'),
(420109, 'Dimension Wand (Lightning Blizzard)', '린드비오르의 예지력', 'craft'),
(420110, 'Dimension Wand (Lightning Beam)', '린드비오르의 인내력', 'craft'),
(420111, 'Dimension Wand (Lighting Storm)', '린드비오르의 마력', 'craft'),
(420112, 'Beleth Loot Box', '발라카스의 완력', 'craft'),
(420113, 'Flames of Hope', '발라카스의 예지력', 'craft'),
(420114, 'Ershabe Box', '발라카스의 인내력', 'craft'),
(420115, 'Nightmare Loot Box', '발라카스의 마력', 'craft'),
(493006, 'Ring of Divine Strike', '신성한 일격의 반지', 'craft'),
(560026, 'Illusionary Tower of Control Teleport Amulet', '환상의 지배의 탑 이동 부적', 'craft'),
(900007, 'Belt of Kronos', '크로노스의 벨트', 'craft'),
(900019, 'Sky T-shirt', '실프의 티셔츠', 'craft'),
(900052, 'Commander Spaulder', '지휘관의 견갑', 'craft'),
(900053, 'Saiha\'s Spaulder', '사이하의 견갑', 'craft'),
(900054, 'Archmage Spaulder', '대마법사의 견갑', 'craft'),
(900056, '\\aFDragon Slayer Gaiters', '\\aF드래곤 슬레이어 각반', 'craft'),
(3000088, 'Magic Doll: Barranca', '마법인형: 바란카', 'treasurebox');
