
-- --------------------------------------------------------

--
-- Table structure for table `app_item_search`
--

CREATE TABLE `app_item_search` (
  `seq` int(11) NOT NULL,
  `item_name` varchar(250) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `item_keyword` varchar(250) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=euckr COLLATE=euckr_korean_ci;

--
-- Dumping data for table `app_item_search`
--

INSERT INTO `app_item_search` (`seq`, `item_name`, `item_keyword`) VALUES
(1, 'Weapon Enchantment Scroll', 'dai'),
(2, 'Armor Enchantment Scroll', 'zel'),
(3, 'Ring of Teleportation Control', 'rotc'),
(4, 'Teleportation Scroll', 'tele'),
(5, 'Red Knight\'s Greatsword', 'rksword'),
(6, 'Sword of Indifference', 'isword'),
(7, 'Ring of Polymorph Control', 'ropc'),
(8, 'Ancient Dark Elf Sword', 'adesword'),
(9, 'Dragon\'s Diamond Box', 'ddbox'),
(10, 'Oriharukon Dagger', 'odagger'),
(11, 'Commander\'s Helmet', 'comhelmet'),
(12, 'Magic Helmet (Strength)', 'homs'),
(13, 'Magic Helmet (Agility)', 'homa'),
(14, 'Speed Enhancement Potion', 'hastepot'),
(15, 'Reinforced Speed Enhancement Potion', 'brave'),
(16, 'Ent\'s Stem', 'estem'),
(17, 'Ent\'s Fruit', 'efruit'),
(18, 'Thebe Osiris\'s Bow', 'osbow'),
(19, 'Thebe Osiris\'s Two-Handed Sword', 'osths'),
(20, 'Thebe Osiris\'s Staff', 'osstaff'),
(21, 'Thebe Osiris\'s Edoryu', 'osedoryu'),
(22, 'Thebe Anubis\'s Ring', 'anring'),
(23, 'Thebe Osiris\'s Belt', 'osbelt'),
(24, 'Steel Boots', 'iboots'),
(25, 'Steel Axe', 'iaxe'),
(26, 'Black Light Edoryu', 'bledoryu'),
(27, 'Blade of Annihilation Chain Sword', 'Pache'),
(28, 'Extreme Chain Sword', 'Geukche'),
(29, 'Illusion Chain Sword', 'Hwanche'),
(30, 'Destruction Chain Sword', 'Seomche'),
(31, 'Indifferent Helmet', 'Mutu'),
(32, 'Indifferent Shield', 'Mubang'),
(33, 'Indifferent Armor', 'Mugap'),
(34, 'Indifferent Cloak', 'Mumang'),
(35, 'Indifferent Longsword', 'Mujang'),
(36, 'Indifferent Boots', 'Mubu'),
(37, 'Divine Priest\'s Robe', 'Sinrop'),
(38, 'Divine Priest\'s Magic Book', 'Sinma'),
(39, 'Divine Priest\'s Boots', 'Sinbu'),
(40, 'Divine Priest\'s Gloves', 'Sinjang'),
(41, 'Divine Priest\'s Cloak', 'Sinmang'),
(42, 'Divine Priest\'s Staff', 'Sinji'),
(43, 'Radiant Warrior Axe', 'Gwangdo'),
(44, 'Kukulkan\'s Spear', 'Kuchang'),
(45, 'Kukulkan\'s Gauntlet', 'Kugan'),
(46, 'Kukulkan\'s Mask', 'Kuma'),
(47, 'Kukulkan\'s Shield', 'Kubang'),
(48, 'Silver Cloak', 'silvercloak'),
(49, 'Cloak of Invisibility', 'coi'),
(50, 'Magic Cloak', 'manacloak'),
(51, 'Fairy Race T-Shirt', 'Yoti'),
(52, 'Bow of Destruction', 'Pajang'),
(53, 'Bow of the Moon', 'Daljang'),
(54, 'Silver Edoryu', 'Euni'),
(55, 'Stone of Magic', 'Madol'),
(56, 'Elemental Jade', 'Jeongok'),
(57, 'Blank Scroll', 'bscroll'),
(58, 'Ancient Warrior\'s Gader', 'Gotusa'),
(59, 'Ancient Archer\'s Gader', 'Myeonggadeo'),
(60, 'Ancient Fairy\'s Bow', 'Goyohwal'),
(61, 'Ancient Leather Armor', 'alm'),
(62, 'Ancient Plate Armor', 'apm'),
(63, 'Ancient Robe', 'arobe'),
(64, 'Ancient Scale Armor', 'Gobineul'),
(65, 'Bloodsucker', 'Beulseo'),
(66, 'Helmet of Magic Resistant', 'homr'),
(67, 'Chain Main of Maic Resistant', 'cmomr'),
(68, 'Strength Belt', 'Wanbel'),
(69, 'Agility Belt', 'Minbel'),
(70, 'Ogre\'s Belt', 'Obel'),
(71, 'Troll\'s Belt', 'Ttobel'),
(72, 'Polymnorph Scroll', 'polyscroll'),
(73, 'Black Wizard\'s Sandals', 'Heuksaen'),
(74, 'Shadow Gloves', 'Geojang'),
(75, 'Power Glove', 'pgloves'),
(76, 'Stone Gloves', 'Doljang'),
(77, 'Crystal Gloves', 'cgloves'),
(78, 'Mana Cloak', 'Mato'),
(79, 'Crystal Staff', 'Suji'),
(80, 'Crystal Dagger', 'Sudan'),
(81, 'Mithril Dagger', 'Midan'),
(82, 'Lich Robe', 'Lilop'),
(83, 'Night Band\'s Two-Handed Sword', 'Nayang'),
(84, 'Night Band\'s Two-Handed Sword', 'Nabal'),
(85, 'Lia\'s Ring', 'Laban'),
(86, 'Silent Sword', 'Chimgum'),
(87, 'Strength Necklace', 'Wanmok'),
(88, 'Knowledge Necklace', 'Jimok'),
(89, 'Charm Necklace', 'Maemok'),
(90, 'Agility Necklace', 'Minmok'),
(91, 'Pumpkin Necklace', 'Homok'),
(92, 'Dagger of Misfortune', 'Agdan'),
(93, 'Boots of Darkness', 'Eobu'),
(94, 'Shadow Boots', 'Geobu'),
(95, 'Transformation Rod', 'Byeonmak'),
(96, 'Greatsword of Doom', 'Padae'),
(97, 'Agility Boots', 'Minbu'),
(98, 'Strength Boots', 'Wanbu'),
(99, 'Wisdom Boots', 'Jibu'),
(100, 'Touch of Chaos', 'Honsol'),
(101, 'Renegade\'s Shield', 'Banbang'),
(102, 'Counter Magic', 'Kamae'),
(103, 'Advance Spirit', 'Abeon'),
(104, 'Advance Spirit', 'Abeon'),
(105, 'Silver Edoryu', 'Euni'),
(106, 'True Ssaulabi Greatsword', 'Jinssa'),
(107, 'True Rapier', 'Jinrei'),
(108, 'Axe of Blood Wind', 'Hyeoldo'),
(109, 'Giant\'s Axe', 'Geodo'),
(110, 'Bow of Destruction', 'Pai'),
(111, 'Zeros\'s Staff', 'Jeji'),
(112, 'Staff of Mana', 'som'),
(113, 'Staff of Strength', 'sos'),
(114, 'Angel\'s Staff', 'Cheonji'),
(115, 'Baphomet\'s Staff', 'Baji'),
(116, 'Demon\'s Staff', 'Deji'),
(117, 'Ice Queen\'s Staff', 'Eolji'),
(118, 'Polearm of Extreme Cold', 'Hokchang'),
(119, 'Trident of Sea God', 'Haechang'),
(120, 'Silver Crow', 'Eunkeu'),
(121, 'Black Crow', 'Heukkeu'),
(122, 'Black Obsidian Keyring', 'Heukki'),
(123, 'Resonance Keyring', 'Gongki'),
(124, 'Cold Keyring', 'Chaengki'),
(125, 'Life Keyring', 'Salki'),
(126, 'Giant Queen Ant\'s Golden Wings', 'Geumnal'),
(127, 'Giant Queen Ant\'s Silver Wings', 'Eunnal'),
(128, 'Philosopher\'s Necklace', 'Hyeonjamok'),
(129, 'Warrior\'s Necklace', 'Tusamok'),
(130, 'Dragon\'s T-Shirt', 'Yongti'),
(131, 'Earth Dragon\'s T-Shirt', 'Jiti'),
(132, 'Wind Dragon\'s T-Shirt', 'Pungti'),
(133, 'Fire Dragon\'s T-Shirt', 'Hwati'),
(134, 'Water Dragon\'s T-Shirt', 'Suti'),
(135, 'Fairy Race Plate Armor', 'Yopan'),
(136, 'Polluted Water', 'Dongmul'),
(137, 'Earth Bind', 'Eoba'),
(138, 'Soul of Frame', 'Solpeu'),
(139, 'Fairy Race Shield', 'Yobang'),
(140, 'Kurtz\'s Sword', 'Keogum'),
(141, 'Deathknight\'s Flame Sword', 'Debul'),
(142, 'Spirit\'s Crystal (Polluted Water)', 'Dongmul'),
(144, 'Wind Blade Dagger', 'Bakal'),
(145, 'Crystal Entity Staff', 'Sugyeolji'),
(146, 'Red Shadow Edoryu', 'Bulgi'),
(148, 'Chronos\'s Terror', 'Keogong'),
(149, 'Hephaestus\'s Despair', 'Hipe'),
(150, 'Titan\'s Wrath', 'Tabun'),
(151, 'Nightmare Bow', 'Akgang'),
(152, 'Counter Barrier', 'Kabae'),
(153, 'Silphe T-Shirt', 'Silphti'),
(154, 'Erzabeth\'s Necklace', 'Ejamok');
