
-- --------------------------------------------------------

--
-- Table structure for table `app_page_info`
--

CREATE TABLE `app_page_info` (
  `uri` varchar(100) NOT NULL,
  `path` varchar(100) DEFAULT NULL,
  `className` varchar(100) NOT NULL,
  `cnbType` int(2) NOT NULL DEFAULT 0,
  `cnbSubType` int(2) NOT NULL DEFAULT 0,
  `needIngame` enum('true','false') NOT NULL DEFAULT 'false',
  `needLauncher` enum('true','false') NOT NULL DEFAULT 'false',
  `needLogin` enum('true','false') NOT NULL DEFAULT 'false',
  `needGm` enum('true','false') NOT NULL DEFAULT 'false',
  `Json` enum('true','false') NOT NULL DEFAULT 'false',
  `fileUpload` enum('true','false') NOT NULL DEFAULT 'false'
) ENGINE=InnoDB DEFAULT CHARSET=euckr COLLATE=euckr_korean_ci;

--
-- Dumping data for table `app_page_info`
--

INSERT INTO `app_page_info` (`uri`, `path`, `className`, `cnbType`, `cnbSubType`, `needIngame`, `needLauncher`, `needLogin`, `needGm`, `Json`, `fileUpload`) VALUES
('/', './appcenter/index.html', 'IndexResponse', 0, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/account/chageCharacter', NULL, 'CharacterChangeResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/account/login', './appcenter/account/login.html', 'LoginResponse', 0, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/account/logout', NULL, 'LogoutResponse', 0, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/account/mypage', './appcenter/account/mypage.html', 'MyPageResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/board', './appcenter/board/index.html', 'BoardResponse', 4, 1, 'false', 'false', 'false', 'false', 'false', 'false'),
('/board/delete', NULL, 'BoardDeleteResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/board/index', './appcenter/board/index.html', 'BoardResponse', 4, 1, 'false', 'false', 'false', 'false', 'false', 'false'),
('/board/insert', NULL, 'BoardInsertResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/board/modify', './appcenter/board/modify.html', 'BoardModifyResponse', 4, 1, 'false', 'false', 'true', 'false', 'false', 'false'),
('/board/update', NULL, 'BoardUpdateResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/board/view', './appcenter/board/view.html', 'BoardViewResponse', 4, 1, 'false', 'false', 'false', 'false', 'false', 'false'),
('/board/write', './appcenter/board/write.html', 'BoardWriteResponse', 4, 1, 'false', 'false', 'true', 'false', 'false', 'false'),
('/board_notice/index', './appcenter/board/index.html', 'BoardResponse', 4, 1, 'false', 'false', 'false', 'false', 'false', 'false'),
('/cash', './appcenter/cash/index.html', 'CashResponse', 0, 0, 'true', 'false', 'true', 'false', 'false', 'false'),
('/cash/auth', './appcenter/cash/auth.html', 'CashAuthResponse', 0, 0, 'true', 'false', 'true', 'false', 'false', 'false'),
('/cash/complete', './appcenter/cash/complete.html', 'CashCompleteResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/contents', './appcenter/content/index.html', 'ContentResponse', 4, 3, 'false', 'false', 'false', 'false', 'false', 'false'),
('/contents/delete', NULL, 'ContentDeleteResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/contents/insert', NULL, 'ContentInsertResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/contents/modify', './appcenter/content/modify.html', 'ContentModifyResponse', 4, 3, 'false', 'false', 'true', 'false', 'false', 'false'),
('/contents/update', NULL, 'ContentUpdateResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/contents/view', './appcenter/content/view.html', 'ContentViewResponse', 4, 3, 'false', 'false', 'false', 'false', 'false', 'false'),
('/contents/write', './appcenter/content/write.html', 'ContentWriteResponse', 4, 3, 'false', 'false', 'true', 'false', 'false', 'false'),
('/coupon', './appcenter/goods/coupon.html', 'CouponResponse', 6, 2, 'false', 'false', 'true', 'false', 'false', 'false'),
('/customer', './appcenter/customer/index.html', 'CustomerResponse', 7, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/customer/support', './appcenter/customer/support.html', 'SupportResponse', 7, 3, 'false', 'false', 'false', 'false', 'false', 'false'),
('/define/account/board', NULL, 'MypageBoardDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/account/loginAdminCheck', NULL, 'LoginAdminDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/account/loginIngame', NULL, 'LoginIngameDefine', 0, 0, 'true', 'false', 'false', 'false', 'true', 'false'),
('/define/account/loginIngameauth', NULL, 'LoginIngameAuthDefine', 0, 0, 'true', 'false', 'false', 'false', 'true', 'false'),
('/define/account/loginIngameInit', NULL, 'LoginIngameInitAuthDefine', 0, 0, 'true', 'false', 'false', 'false', 'true', 'false'),
('/define/account/loginReCheck', NULL, 'LoginWebDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/alim/delete', NULL, 'AlimDeleteDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/board', NULL, 'BoardDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/board/commentDelete', NULL, 'BoardCommentDeleteDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/board/commentInsert', NULL, 'BoardCommentInsertDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/board/commentLike', NULL, 'BoardCommentLikeDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/board/like', NULL, 'BoardLikeDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/cash/charge', NULL, 'CashChargeDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/contents', NULL, 'ContentDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/contents/commentDelete', NULL, 'ContentCommentDeleteDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/contents/commentInsert', NULL, 'ContentCommentInsertDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/contents/commentLike', NULL, 'ContentCommentLikeDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/contents/like', NULL, 'ContentLikeDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/contents/more', NULL, 'ContentMoreDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/coupon', NULL, 'CouponDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/coupon/create', NULL, 'CouponCreateDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'false'),
('/define/coupon/use', NULL, 'CouponUseDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/customer', NULL, 'CustomerDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/customer/comment/insert', NULL, 'CustomerCommentInsertDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'false'),
('/define/customer/delete', NULL, 'CustomerDeleteDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/customer/insert', NULL, 'CustomerInsertDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/customer/normal', NULL, 'CustomerNormalDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/customer/normal/delete', NULL, 'CustomerNormalDeleteDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'false'),
('/define/customer/normal/insert', NULL, 'CustomerNormalInsertDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'false'),
('/define/customer/normal/update', NULL, 'CustomerNormalUpdateDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'false'),
('/define/customer/view', NULL, 'CustomerViewDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/editor/delete', NULL, 'FileDeleteDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/editor/insertcancel', NULL, 'FileInsertCancelDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/editor/updatecancel', NULL, 'FileUpdateCancelDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/editor/upload', NULL, 'FileUploadDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'true'),
('/define/gamestart', NULL, 'GameStartDefine', 0, 0, 'false', 'true', 'true', 'false', 'true', 'false'),
('/define/gift', NULL, 'GiftDefine', 0, 0, 'true', 'false', 'true', 'false', 'true', 'false'),
('/define/gm', NULL, 'GMDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'false'),
('/define/gm/banuser', NULL, 'GMUserBanDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'false'),
('/define/gm/deleteitem', NULL, 'GMItemDeleteDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'false'),
('/define/gm/deleteuser', NULL, 'GMUserDeleteDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'false'),
('/define/gm/reportdelete', NULL, 'GMReportDeleteDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'false'),
('/define/gm/supportBankResponse', NULL, 'GMSupportBankResponseDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'false'),
('/define/gm/supportdelete', NULL, 'GMSupportDeleteDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'false'),
('/define/gm/supportfinish', NULL, 'GMSupportFinishDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'false'),
('/define/goods', NULL, 'GoodsDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/goods/buy', NULL, 'GoodsBuyDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/guide/boss', NULL, 'GuideBossDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/item-search/list', NULL, 'ShopListDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/item-search/view-list', NULL, 'ShopViewListDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/keyword', NULL, 'KeywordDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/logout', NULL, 'LogoutDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/notice', NULL, 'NoticeDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/notice/more', NULL, 'NoticeMoreDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/pitch', NULL, 'PitchDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/pitch/commentDelete', NULL, 'PitchCommentDeleteDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/pitch/commentInsert', NULL, 'PitchCommentInsertDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/pitch/commentLike', NULL, 'PitchCommentLikeDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/pitch/like', NULL, 'PitchLikeDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/pitch/more', NULL, 'PitchMoreDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/pledge', NULL, 'BloodPledgeDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/powerbook/insert', NULL, 'PowerbookInsertDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'true'),
('/define/powerbook/list', NULL, 'PowerbookListDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/powerbook/update', NULL, 'PowerbookUpdateDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'true'),
('/define/promotion/delete', NULL, 'PromotionDeleteDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'false'),
('/define/promotion/insert', NULL, 'PromotionInsertDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'true'),
('/define/promotion/update', NULL, 'PromotionUpdateDefine', 0, 0, 'false', 'false', 'true', 'true', 'true', 'true'),
('/define/rank', NULL, 'RankDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/report/insert', NULL, 'ReportInsertDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/search/list', NULL, 'SearchListDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/suggest', NULL, 'SuggestDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/support/agree', NULL, 'SupportAgreeDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/support/msg', NULL, 'SupportMessageDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/define/support/request', NULL, 'SupportBankRequestDefine', 0, 0, 'true', 'false', 'true', 'false', 'true', 'false'),
('/define/trade', NULL, 'TradeDefine', 0, 0, 'false', 'false', 'false', 'false', 'true', 'false'),
('/define/trade/status', NULL, 'TradeStatusDefine', 0, 0, 'false', 'false', 'true', 'false', 'true', 'false'),
('/download', './appcenter/download/connect.html', 'DownLoadResponse', 5, 1, 'false', 'false', 'false', 'false', 'false', 'false'),
('/download/emblem', './appcenter/download/emblem.html', 'DownLoadEmblemResponse', 5, 2, 'false', 'false', 'false', 'false', 'false', 'false'),
('/gift/form', './appcenter/goods/gift.html', 'GiftResponse', 0, 0, 'true', 'false', 'true', 'false', 'false', 'false'),
('/gm', './appcenter/gm/gm.html', 'GMResponse', 8, 1, 'false', 'false', 'true', 'true', 'false', 'false'),
('/goods', './appcenter/goods/index.html', 'GoodsResponse', 6, 1, 'false', 'false', 'false', 'false', 'false', 'false'),
('/goods/coupon', './appcenter/goods/coupon.html', 'CouponResponse', 6, 2, 'false', 'false', 'true', 'false', 'false', 'false'),
('/goods/view', './appcenter/goods/view.html', 'GoodsViewResponse', 6, 1, 'false', 'false', 'false', 'false', 'false', 'false'),
('/guide', './appcenter/guide/index.html', 'GuideResponse', 2, 2, 'false', 'false', 'false', 'false', 'false', 'false'),
('/guide/delete', NULL, 'GuideDeleteResponse', 0, 0, 'false', 'false', 'true', 'true', 'false', 'false'),
('/guide/insert', NULL, 'GuideInsertResponse', 0, 0, 'false', 'false', 'true', 'true', 'false', 'false'),
('/guide/modify', './appcenter/guide/modify.html', 'GuideModifyResponse', 2, 2, 'false', 'false', 'true', 'true', 'false', 'false'),
('/guide/update', NULL, 'GuideUpdateResponse', 0, 0, 'false', 'false', 'true', 'true', 'false', 'false'),
('/guide/write', './appcenter/guide/write.html', 'GuideWriteResponse', 2, 2, 'false', 'false', 'true', 'true', 'false', 'false'),
('/index', './appcenter/index.html', 'IndexResponse', 0, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/ingame', './appcenter/index.html', 'IndexResponse', 0, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/ingame/index', './appcenter/index.html', 'IndexResponse', 0, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/ingame/item/itemSearch', NULL, 'ShopResponse', 3, 1, 'false', 'false', 'true', 'false', 'false', 'false'),
('/item', NULL, 'ShopResponse', 3, 1, 'false', 'false', 'true', 'false', 'false', 'false'),
('/item/itemSearch', NULL, 'ShopResponse', 3, 1, 'false', 'false', 'true', 'false', 'false', 'false'),
('/itemSearch', NULL, 'ShopResponse', 3, 1, 'false', 'false', 'true', 'false', 'false', 'false'),
('/login', './appcenter/account/login.html', 'LoginResponse', 0, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/login_admin', './appcenter/account/login_admin.html', 'LoginAdminResponse', 0, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/login_ingame', './appcenter/account/login_ingame.html', 'LoginIngameResponse', 0, 0, 'true', 'false', 'false', 'false', 'false', 'false'),
('/logout', NULL, 'LogoutResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/my/board', './appcenter/board/index.html', 'BoardResponse', 4, 1, 'false', 'false', 'false', 'false', 'false', 'false'),
('/my/index', './appcenter/index.html', 'IndexResponse', 0, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/my/item-search', NULL, 'ShopResponse', 3, 1, 'false', 'false', 'true', 'false', 'false', 'false'),
('/my/item-search/view', './appcenter/shop/view.html', 'ShopViewResponse', 3, 1, 'false', 'false', 'true', 'false', 'false', 'false'),
('/my/notice', './appcenter/notice/index.html', 'NoticeResponse', 1, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/my/pm', './appcenter/fix/index.html', 'FixResponse', 0, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/mypage', './appcenter/account/mypage.html', 'MyPageResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/notice', './appcenter/notice/index.html', 'NoticeResponse', 1, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/notice/delete', NULL, 'NoticeDeleteResponse', 0, 0, 'false', 'false', 'true', 'true', 'false', 'false'),
('/notice/insert', NULL, 'NoticeInsertResponse', 0, 0, 'false', 'false', 'true', 'true', 'false', 'false'),
('/notice/modify', './appcenter/notice/modify.html', 'NoticeModifyResponse', 1, 0, 'false', 'false', 'true', 'true', 'false', 'false'),
('/notice/update', NULL, 'NoticeUpdateResponse', 0, 0, 'false', 'false', 'true', 'true', 'false', 'false'),
('/notice/view', './appcenter/notice/view.html', 'NoticeViewResponse', 1, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/notice/write', './appcenter/notice/write.html', 'NoticeWriteResponse', 1, 0, 'false', 'false', 'true', 'true', 'false', 'false'),
('/outgame/create', NULL, 'AccountCreateDefine', 0, 0, 'false', 'true', 'false', 'false', 'true', 'false'),
('/outgame/engine', NULL, 'EngineLogDefine', 0, 0, 'false', 'true', 'false', 'false', 'true', 'false'),
('/outgame/info', NULL, 'ConnectorInfoDefine', 0, 0, 'false', 'true', 'false', 'false', 'true', 'false'),
('/outgame/login', NULL, 'LoginDefine', 0, 0, 'false', 'true', 'false', 'false', 'true', 'false'),
('/outgame/loginmerge', NULL, 'LoginMergeDefine', 0, 0, 'false', 'true', 'false', 'false', 'true', 'false'),
('/outgame/process', NULL, 'ProcessMergeDefine', 0, 0, 'false', 'true', 'false', 'false', 'true', 'false'),
('/pitch', './appcenter/pitch/index.html', 'PitchResponse', 4, 4, 'false', 'false', 'false', 'false', 'false', 'false'),
('/pitch/delete', NULL, 'PitchDeleteResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/pitch/insert', NULL, 'PitchInsertResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/pitch/modify', './appcenter/pitch/modify.html', 'PitchModifyResponse', 4, 4, 'false', 'false', 'true', 'false', 'false', 'false'),
('/pitch/update', NULL, 'PitchUpdateResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/pitch/view', './appcenter/pitch/view.html', 'PitchViewResponse', 4, 4, 'false', 'false', 'false', 'false', 'false', 'false'),
('/pitch/write', './appcenter/pitch/write.html', 'PitchWriteResponse', 4, 4, 'false', 'false', 'true', 'false', 'false', 'false'),
('/pm', './appcenter/fix/index.html', 'FixResponse', 0, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/powerbook', './appcenter/powerbook/index.html', 'PowerbookResponse', 2, 1, 'false', 'false', 'false', 'false', 'false', 'false'),
('/powerbook/delete', NULL, 'PowerbookDeleteResponse', 0, 0, 'false', 'false', 'true', 'true', 'false', 'false'),
('/powerbook/modify', './appcenter/powerbook/modify.html', 'PowerbookModifyResponse', 2, 1, 'false', 'false', 'true', 'true', 'false', 'false'),
('/powerbook/search', NULL, 'PowerbookSearchResponse', 2, 1, 'false', 'false', 'false', 'false', 'false', 'false'),
('/powerbook/write', './appcenter/powerbook/write.html', 'PowerbookWriteResponse', 2, 1, 'false', 'false', 'true', 'true', 'false', 'false'),
('/protect', './appcenter/protect/index.html', 'ProtectResponse', 0, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/search', './appcenter/search/index.html', 'SearchResponse', 0, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/search/community', './appcenter/search/community.html', 'SearchCommunityResponse', 0, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/search/content', './appcenter/search/content.html', 'SearchContentResponse', 0, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/search/trade', './appcenter/search/trade.html', 'SearchTradeResponse', 0, 0, 'false', 'false', 'false', 'false', 'false', 'false'),
('/trade', './appcenter/trade/index.html', 'TradeResponse', 4, 2, 'false', 'false', 'false', 'false', 'false', 'false'),
('/trade/buyRegist', NULL, 'TradeBuyRegistResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/trade/delete', NULL, 'TradeDeleteResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/trade/insert', NULL, 'TradeInsertResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/trade/modify', './appcenter/trade/modify.html', 'TradeModifyResponse', 4, 2, 'false', 'false', 'true', 'false', 'false', 'false'),
('/trade/receive', NULL, 'TradeReceiveResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/trade/send', NULL, 'TradeSendResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/trade/update', NULL, 'TradeUpdateResponse', 0, 0, 'false', 'false', 'true', 'false', 'false', 'false'),
('/trade/view', './appcenter/trade/view.html', 'TradeViewResponse', 4, 2, 'false', 'false', 'false', 'false', 'false', 'false'),
('/trade/write', './appcenter/trade/write.html', 'TradeWriteResponse', 4, 2, 'false', 'false', 'true', 'false', 'false', 'false'),
('/world/pledge', './appcenter/world/pledge.html', 'BloodPledgeResponse', 3, 3, 'false', 'false', 'false', 'false', 'false', 'false'),
('/world/rank', './appcenter/world/rank.html', 'RankResponse', 3, 2, 'false', 'false', 'false', 'false', 'false', 'false');
