
-- --------------------------------------------------------

--
-- Table structure for table `app_guide`
--

CREATE TABLE `app_guide` (
  `id` int(2) NOT NULL DEFAULT 0,
  `title` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `content` mediumtext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=euckr COLLATE=euckr_korean_ci;

--
-- Dumping data for table `app_guide`
--

INSERT INTO `app_guide` (`id`, `title`, `content`) VALUES
(1, 'Currency Types', '<p><b>1. Adena</b></p><p><b><br></b></p><p><b>2. Berry</b></p><p><b><br></b></p><p><b>3. TAM</b></p><p><b><br></b></p><p><b>4. Einhasad Points</b></p><p><b><br></b></p><p><b>5. Pixie\'s Golden Feather - PC Room Buff</b></p><p><b><br></b></p><p><b>6. Hero\'s Coin - Sponsor Coin</b></p><p><b><br></b></p><p><b>7. N-Coin - App Center Lineage N Shop</b></p>'),
(2, 'Shop Information', '<p><b>1. In-game - Use the UI on the right side <font color=\"#0000ff\">\'Alarm\'&nbsp;</font>to access the shop.</b></p><p><br></p><p><b>2. App Center - Lineage N Shop</b></p><p><b><br></b></p><p><b>3. Sponsor Shop - Giran Town Square 11:00 AM</b></p>'),
(3, 'Hunting Ground Information', '<p><b>1. Dark Dragon Dungeon - 9 AM to 12 AM</b><br></p><p><br></p><p><b>2. Forgotten Island (Local) - Sat, Sun 9 AM to 6 PM / Level 85 restriction</b></p><p><b><br></b></p><p><b>3. Land of Forsaken People (Local) - Level 75 restriction</b></p><p><b><br></b></p><p><b>4. Land of Forsaken People West (Inter) - Levels 89 to 91 / 6:30 PM to 9 PM / Daily 1-hour limit</b></p><p><b><br></b></p><p><b>5. Land of Forsaken People East (Inter) - Levels 89 to 93 / 6:30 PM to 9 PM / Daily 1-hour limit</b></p><p><b><br></b></p><p><b>6. Tower of Dominion (Inter) - 7 PM to 12 AM</b></p><p><b><br></b></p><p><b>7. Queen Ant\'s Hideout (Inter) - Tuesday 8:05 PM</b></p><p><b><br></b></p><p><b><font color=\"#ff0000\">Daily dungeon times reset at 6 AM.</font></b></p>'),
(4, 'Regulation Information', '<p><b>1. Acts detrimental to the server or administrators, 1st offense <font color=\"#0000ff\">Hardware Ban</font></b></p><p><b><br></b></p><p><b>2. Use of illegal programs, 1st offense <font color=\"#0000ff\">Hardware Ban</font></b></p><p><b>(This server can check all user processes.)</b></p><p><b><br></b></p><p><b>3. Exploiting bugs and glitches, 1st offense <font color=\"#000000\">Warning</font>, 2nd offense <font color=\"#0000ff\">1-day suspension,</font> 3rd offense <font color=\"#0000ff\">IP Ban</font></b></p><p><b><br></b></p><p><b>4. Severe profanity, harassment in global chat, 1st offense chat mute for 1 hour, 2nd offense chat mute for 10 hours, 3rd offense prison for 1 day</b></p><p><b><br></b></p><p><b>5. Real money trade fraud results in <font color=\"#0000ff\">Hardware Ban</font> of the character</b></p><p><b>(Determined by the administration with evidence)</b></p><p><b><br></b></p><p><b style=\"\"><font color=\"#ff0000\" style=\"background-color: rgb(255, 255, 255);\">We do not intervene in player behavior, such as external chatting (profanity) during battles.</font></b></p>'),
(5, 'Reward Information', '<p><b>1. Reporting bugs and errors will result in differential rewards of <font color=\"#ff00ff\">\'Hero\'s Coins\'</font></b></p><p><b><br></b></p><p><b>2. Ranking rewards (next turn)</b></p><p>&nbsp; &nbsp; <font color=\"#9c00ff\">1st</font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color=\"#9c00ff\">5th Stage Blessing Doll</font></p><p><font color=\"#9c00ff\">&nbsp; &nbsp; 2nd</font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color=\"#9c00ff\">5th Stage Doll</font></p><p><font color=\"#9c00ff\">&nbsp; &nbsp; 3rd&nbsp; &nbsp; </font>&nbsp;&nbsp;&nbsp;&nbsp;<font color=\"#9c00ff\">5th Stage Doll</font></p><p><font color=\"#ff0000\">&nbsp; &nbsp; 4th&nbsp; &nbsp; </font>&nbsp;&nbsp;&nbsp;&nbsp;<font color=\"#ff0000\">4th Stage Blessing Doll</font></p><p><font color=\"#ff0000\">&nbsp; &nbsp; 5th&nbsp; &nbsp; </font>&nbsp;&nbsp;&nbsp;&nbsp;<font color=\"#ff0000\">4th Stage Blessing Doll</font></p><p><font color=\"#ff0000\">&nbsp; &nbsp; 6th&nbsp; &nbsp; </font>&nbsp;&nbsp;&nbsp;&nbsp;<font color=\"#ff0000\">4th Stage Doll</font></p><p><font color=\"#ff0000\">&nbsp; &nbsp; 7th&nbsp; &nbsp; </font>&nbsp;&nbsp;&nbsp;&nbsp;<font color=\"#ff0000\">4th Stage Doll</font></p><p><font color=\"#9c00ff\">&nbsp; &nbsp; </font><font color=\"#0000ff\">8th&nbsp; &nbsp; </font>&nbsp;&nbsp;&nbsp;&nbsp;<font color=\"#0000ff\">3rd Stage Blessing Doll</font></p><p><font color=\"#0000ff\">&nbsp; &nbsp; 9th</font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color=\"#0000ff\">3rd Stage Blessing Doll</font></p><p><font color=\"#0000ff\">&nbsp; &nbsp; 10th</font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color=\"#0000ff\">3rd Stage Doll</font><br></p>'),
(6, 'Miscellaneous Information', '<p><b>1. When hunting boss monsters, you can obtain an <font color=\"#ff0000\">\'Olym\'s Jewelry Enchantment Scroll Box\'</font>.</b></p><p><b><br></b></p><p><b>2. Rankings are updated every <font color=\"#0000ff\" style=\"background-color: rgb(255, 255, 255);\">6 hours</font> (6 AM, 12 PM, 6 PM, 12 AM).</b></p><p><b><br></b></p><p><b>3. Server updates and directions are aligned as much as possible with the <font color=\"#0000ff\">live server.</font></b></p><p><b><br></b></p><p><b>4. When using other servers, the client may be <font color=\"#0000ff\" style=\"background-color: rgb(255, 255, 255);\">tampered</font>, so in case of errors or inability to connect, please <font color=\"#0000ff\" style=\"background-color: rgb(255, 255, 255);\">reinstall</font> the client.</b></p>');
